language: python
python:
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

services:
  - postgresql

env:
  global:
    - DATABASE_URL='postgres://postgres:@localhost:/travis_ci_test'
    - SECRET_KEY='aadc-t8j*i5a7^y9@d^$at#g0!j_h=h++5stj=nb7z8u#l_y#&'
    - DEBUG='True'
  matrix:
    - DJANGO=1.9.2
    - DJANGO=latest

matrix:
  allow_failures:
    - python: "nightly"

# command to install dependencies
install:
  - if [[ "$DJANGO" != "latest" ]] ; then pip install -q Django==$DJANGO; fi
  - pip install -r django/requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script:
  - python --version
 
deploy:
  edge: true
  provider: cloudfoundry
  username:
    secure: pcHLbaVxKbftTwVm0lhR8yPEhfCBfkrhhOXqw9tyt0FFOC/NDBF5pXDzj2NA9t8N+7cXasBUOvJQx1wCQ58zLrrDXel7cWdE62MHmSQiu/j0GY0CWTsyN701BsVL2kTcvWPczmSuFoIzhxQponRq5w/olyUaI27VCqG7GMSpgypux/WAP4pbhQs7EWoA1sfwfsiaeMY4eY5DSsk4F865Q0u1L627d66W3EUsAZkV5Lhye9GvHfYWQrf/by4jMe5sc4j/faxpD8W3xuN/u3dTXIMJOhKqRUxhqvCLwBWiONM/gCgCWIcT/IcneycjoPj1r0Sfzgg4/bRzG4GaWfagipRrqcsY4kddNQ4E3xjMmAKvq6khJaskFc2g9N7vabh2rcp6xdPhT/MpM+Gyq6EWjAjrnEml1t4ef4/Fgp7dPwoUO0jHzP2HSWnXoa3cODGvom2JMZyu+D+gZp7mca01K7xY4XElCkQhBVQFMTkkkBANT6eadisxMZGPEfIBzzL/whDdo5gs2NJLScE0eDFWEj+9YIMFDksi7m9P0qWYQ7rrIzr1v9wIT+iD6EKpn7aB6y8bOceoyl0ZNwsee9N6ZMjH25nbcDp+hDIkR7oYEhb18RetSmaruZobRRKr6CA48SCDIYuw+yVmxzglArvIyTZht/9pkl/VWlqvaLUJbnY=
  password:
    secure: IC6P3AepS7cMPsHZM+hN0tb0ZvbKiSEEVASa2jTjpV5rklP+SbHw3GWqe1XzoMurpoyLWrVexmAWy/JfhkWuiTHJS12Jk2u6HejVNlMB/7Te2yqci1f/F5fvEexiNfqb4sORIjgao629ObrnfuCcS+x77qb7Ud0nHUgzDMe1ga0owIkhQsdYbiStGWv5uf/WnopNRWBqkKBzRiTVVv8T3DjBqKJmKlV5kMZnQI7e+9qPVv0JMXpj/DbBcXoRf5c/fX1dbvay6VykLcKZvgw8hrpD9Ba0WyclreANHuLyfXsFyywB4h9jBU/74Lt5aswMXfdqXfthpjYklguY6IrIW2iWSsU3bnjg7VohvuJ1lk9XtcI0DzddANFpxPwFeXK6pD2RJIt1d0BXoF8jQrN+wq3o5ld+ZdbcO2yQY6O4fNhVLTQq67si9Ja2wmlr4jK7m9YAaeKv2H/fkLexF0lRVg7t2glcDZbEscrfSGhzZPLx2+iNfFi81RchzzSiA1wCEy2kNdzVjXu85SJnvYIwsnR+1UOsvpCCOyFW0BoRvJ4nDmiecCJmTscLks+xzYHL8TtKhlovpeMdwL65Y1C3l37lzYzNYoP5weL86c1fhwTMxTnceg7by4LO/khPQ3X8k7zUWFVaEGBqCiaLyMWtq9XYEdnHnetKu5PtsaZX3F8=
  api: https://api.run.pivotal.io
  organization: EVP
  space: EMC
  manifest: manifest-travis.yml
  on:
    branch: travis
