# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phoenix.custom_storages
import uuid
import vault.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('filename', models.FileField(storage=phoenix.custom_storages.SecureStorage(), upload_to=vault.models.DocumentFilename)),
                ('downloads', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='documentgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='vault.DocumentGroup'),
        ),
    ]
