# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import phoenix.custom_storages
import uuid
import whiteboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=320)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(storage=phoenix.custom_storages.SecureStorage(), upload_to=whiteboard.models.WhiteboardImageName)),
                ('img_large', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='WhiteboardImages/thumb')),
                ('img_medium', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='WhiteboardImages/thumb')),
                ('img_small', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='WhiteboardImages/thumb')),
                ('img_thumb', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='WhiteboardImages/thumb')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
