# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import mytwitter.models
import phoenix.custom_storages
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('text', models.TextField(max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('screenname', models.CharField(blank=True, max_length=15)),
                ('from_twitter', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TweetPic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.ImageField(storage=phoenix.custom_storages.SecureStorage(), upload_to=mytwitter.models.TweetPictureName)),
                ('pic_large', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='TweetPictures/thumb')),
                ('pic_medium', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='TweetPictures/thumb')),
                ('pic_small', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='TweetPictures/thumb')),
                ('pic_thumb', django_resized.forms.ResizedImageField(blank=True, storage=phoenix.custom_storages.SecureStorage(), upload_to='TweetPictures/thumb')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='mytwitter.Tweet')),
            ],
        ),
    ]
